# -*- coding: utf-8 -*-
"""MultiLabelRegnet

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jaJComJg5USeBiBikDz7Y_T4Zo-JEwbi
"""

from torch import nn, Tensor
import timm

class MultiLabelRegnet(nn.Module):
    def __init__(self):
        super(MultiLabelRegnet, self).__init__()
        self.conv2d = nn.Conv2d(1, 3, 3, stride=1)
        self.regnet_32 = timm.create_model('regnetx_032', pretrained=True)
        self.FC = nn.Linear(1000, 26)

    def forward(self, x):
        
        x = F.relu(self.conv2d(x))        
        x = F.relu(self.regnet_32(x))        
        x = torch.sigmoid(self.FC(x))
        return x